## 3 rivers data output
## Created: October 13, 2021
## Heili Lowman

# The following code will do some examination of the output
# of the 3 site dataset run through the Ricker model to examine
# the effects of gappiness on time series.

# Load packages
lapply(c("calecopal", "cowplot",
         "lubridate","tidyverse", "reshape2",
         "PerformanceAnalytics","jpeg","grid",
         "rstan","bayesplot","shinystan", "here",
         "ggrepel", "patchwork"), require, character.only=T)

#### Data Import & Processing ####

# Load dataset loaded into STAN.
data_in <- readRDS("data_working/df_3sites.rds")

# Load datasets generated by STAN.
# output using full timeseries
data_out <- readRDS("data_teton/stan_3rivers_output_Ricker_2021_10_13.rds")
# output using timeseries with gaps
data_out_g <- readRDS("data_teton/stan_3rivers_gaps_output_Ricker_2021_10_13.rds")
# output of grouped yearly data for one site
data_out_y <- readRDS("data_teton/stan_1river_years_output_Ricker_2021_10_13.rds")

# Load dataset with site information.
data_info <- readRDS("data_working/NWIS_3sitesinfo_subset.rds")

# Make sure shinystan is working properly by testing at one site.
launch_shinystan(data_out$nwis_02266300)

# Function of the above to pull out data of interest from
# all sites.
extract_params <- function(df){
  extract(df, c("r","lambda","s","c","sig_p","sig_o"))
}

# And now map this to the output lists.
data_out_params <- map(data_out, extract_params)
data_out_params_g <- map(data_out_g, extract_params)
data_out_params_y <- map(data_out_y, extract_params)

# And create a dataframe
data_out_params_df <- map_df(data_out_params, ~as.data.frame(.x), .id="site_name") %>%
  # and add "K" to it, calculating for each individual iteration
  mutate(k = (-1*r)/lambda)

# And now to calculate means by site.
data_means <- data_out_params_df %>%
  group_by(site_name) %>%
  summarize(r_mean = mean(r),
            k_mean = mean(k),
            s_mean = mean(s),
            c_mean = mean(c),
            sigp_mean = mean(sig_p),
            sigo_mean = mean(sig_o))

# And now to bind the values with site attributes.
data_together <- left_join(data_means, data_info, by = "site_name")

# Export dataset
saveRDS(data_together, file = "data_working/teton_34rivers_model_parameters_090821.rds")

# Also, need to extract divergence information from the sites.
# Code available at : mc-stan.org/users/documentation/case-studies/divergences_and_bias.html
# Doing this at one site first to make sure it works - note nwis_01632900 has 8 divergences.
# Note - you need TWO underscores after 'divergent'
divergent <- get_sampler_params(data_out$nwis_01632900, inc_warmup=FALSE)[[1]][,'divergent__']
sum(divergent)
# Yay, it works!!

# Now, to map this to the whole dataset
extract_divergences <- function(df){
  divergent <- get_sampler_params(df, inc_warmup=FALSE)[[1]][,'divergent__']
  sum(divergent)
}

# And now map this to the entire output list.
# this function can also be finicky, and require you to quit R and re-load everything back in.
data_out_divs <- map(data_out, extract_divergences)

# And create a dataframe
data_out_divs_df <- map_df(data_out_divs, ~as.data.frame(.x), .id="site_name") %>%
  rename(divergences = `.x`)

# Export dataset
saveRDS(data_out_divs_df, file = "data_working/teton_34rivers_model_divergences_091621.rds")

####      Figures         ####

#### All Parameter Comparisons ####

# Now, to compare growth and disturbance parameters
# r vs. c
fig5a <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = c_mean, y = r_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) + # custom colors
  labs(x = "Critical Discharge (c)",
       y = "Maximum Growth Rate (r)") +
  geom_text_repel(data = subset(data_together, r_mean > 0.3), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5a

# r vs. s
fig5b <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = s_mean, y = r_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Sensitivity of Persistence Curve (s)",
       y = "Maximum Growth Rate (r)") +
  geom_text_repel(data = subset(data_together, r_mean > 0.3 | s_mean > 300), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5b

# k vs. c
fig5c <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = c_mean, y = k_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Critical Discharge (c)",
       y = "Carrying Capacity (K)") +
  geom_text_repel(data = subset(data_together, k_mean > 30), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5c

# k vs. s
fig5d <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = s_mean, y = k_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Sensitivity of Persistence Curve (s)",
       y = "Carrying Capacity (K)") +
  geom_text_repel(data = subset(data_together, k_mean > 30 | s_mean > 300), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5d

full_fig5 <- (fig5a + fig5b) / (fig5c + fig5d) +
  plot_annotation(tag_levels = 'A')

full_fig5

# ggsave(full_fig5,
#        filename = "figures/teton_34sites/rk_vs_cs.jpg",
#        width = 11,
#        height = 11)

#### Covariate data quality ####

plotting_covar <- function(x) {
  
  # create a dataframe at each site
  df.1 <- x
  
  # join with site information
  df <- left_join(df.1, data_info, by = "site_name")
  
  # create a vector of the available years of data
  years <- unique(df$year)
  
  # loop over each year of data
  for(z in years){
    
    # subset the data by year
    subset <- subset(df, year == z) # subset the larger dataset by each year
    
    # create a 4-paneled plot with gross primary production, discharge, temperature, and light
    # a.k.a. data inputs (prior to fitting the model)
    p <- plot_grid(
    
    ggplot(subset, aes(date, GPP))+
      geom_point(color="chartreuse4", size=2)+
      geom_errorbar(aes(ymin = GPP.lower, ymax = GPP.upper), width=0.2,color="darkolivegreen4")+
      labs(y=expression('GPP (g '*~O[2]~ m^-2~d^-1*')'), 
           title = df$long_name.y[1],
           subtitle = df$site_name[1])+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, Q))+
      geom_line(size=1.5, color="deepskyblue4")+
      labs(y="Q (cms)")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, temp))+
      geom_line(size=1.5, color="#A11F22")+
      labs(y="Water Temp (C)")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, light))+
      geom_point(size=2, color="darkgoldenrod3")+
      labs(y="Incoming Light", x="Date")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.text = element_text(size=12),
            axis.title = element_text(size=12)),
    ncol=1, align="hv")
  
  # display plots
  print(p) 
  
  # save and export plots
  file.name <- paste0("figures/teton_34sites/site_covariate_plots/",df$site_name[1],"_",z,"_covar.jpg",sep = "") # create file name
  
  # set specifications for size and resolution of your figure
  ggsave(p,
         filename = file.name,
         width = 8,
         height = 8)
  
  } # close out for-loop
  
} # close out function

# test to be sure the function works at a single site
plotting_covar(data_in$nwis_02266200)

# And now map this to the entire data_in list.
map(data_in, plotting_covar)

#### Divergences ####

# fig_div <- ggplot(data_out_divs_df, aes(x = bin_cat, fill = bin_cat)) + # base plot
#   geom_histogram(stat = "count") + # divergences histogram
#   scale_fill_manual(values = cal_palette("fire", n = 7, type = "continuous")) + # custom colors
#   labs(x = "Number of Divergences",
#        y = "Site Count") +
#   scale_y_continuous(breaks=seq(0, 10, 1)) + # fix y axis labels
#   theme_classic() + # remove grid
#   theme(legend.position = "none")
# 
# fig_div
# DONT USE THIS FIGURE YET - for whatever reason, the 
# number of divergences on the shinystan app does not
# match the output of the above function from the mc-stan
# help document....

# For the meeting on 9/27/2021, I will be using the output of shinystan since,
# it's the larger/more conservative

data_divs_join <- left_join(data_years, data_out_diff_divs, by = "site_name")

# Adding category to make a nicer looking plots
data_divs_join <- data_divs_join %>%
  mutate(bin_cat = factor(case_when(div_shinyStan == 0 ~ "0",
                                    div_shinyStan > 0 & div_shinyStan <= 50 ~ "0-50",
                                    div_shinyStan > 50 & div_shinyStan <= 100 ~ "50-100",
                                    div_shinyStan > 100 & div_shinyStan <= 1000 ~ "100-1000",
                                    div_shinyStan > 1000 & div_shinyStan <= 2500 ~ "1000-2500",
                                    div_shinyStan > 2500 ~ "2500+",
                                    TRUE ~ "NA"),
                          levels = c("0", "0-50", "50-100", "100-1000", "1000-2500", "2500+")))

fig_yrs_divs <- ggplot(data_divs_join,
                       aes(x = n, y = div_shinyStan, fill = bin_cat, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("fire", n = 6, type = "continuous")) + # custom colors
  labs(x = "Years of Available Data",
       y = "Divergent Transitions") +
  geom_text_repel(data = subset(data_divs_join, n > 5 & div_shinyStan > 2000), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig_yrs_divs

# Also creating figure of hydrology vs. divergences

# Calculate coefficient of variation (sd/mean) for each site
test_site <- data_in$nwis_01608500
test_sd <- sd(test_site$Q)
test_mean <- mean(test_site$Q)
test_cv <- test_sd/test_mean

# Now, to create a function...
calc_coeff_var <- function(df){
  sd <- sd(df$Q)
  mean <- mean(df$Q)
  sd/mean
}

# And now map this to the entire output list.
data_cvs <- map(data_in, calc_coeff_var)
# yipee

# And create a dataframe
data_cvs_divs <- map_df(data_cvs, ~as.data.frame(.x), .id="site_name") %>%
  rename(coeff_var = `.x`) %>%
  left_join(data_out_diff_divs, by = "site_name")

# Adding same categories as above to make a nicer looking plots
data_cvs_divs <- data_cvs_divs %>%
  mutate(bin_cat = factor(case_when(div_shinyStan == 0 ~ "0",
                                    div_shinyStan > 0 & div_shinyStan <= 50 ~ "0-50",
                                    div_shinyStan > 50 & div_shinyStan <= 100 ~ "50-100",
                                    div_shinyStan > 100 & div_shinyStan <= 1000 ~ "100-1000",
                                    div_shinyStan > 1000 & div_shinyStan <= 2500 ~ "1000-2500",
                                    div_shinyStan > 2500 ~ "2500+",
                                    TRUE ~ "NA"),
                          levels = c("0", "0-50", "50-100", "100-1000", "1000-2500", "2500+")))

fig_cv_divs <- ggplot(data_cvs_divs,
                       aes(x = coeff_var, y = div_shinyStan, fill = bin_cat, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("fire", n = 6, type = "continuous")) + # custom colors
  labs(x = "Coefficient of Variation in Discharge",
       y = "Divergent Transitions") +
  geom_text_repel(data = subset(data_cvs_divs, coeff_var > 3 | div_shinyStan > 3000), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig_cv_divs

# creating composite figure for export
fig_div_full <- fig_yrs_divs + fig_cv_divs +
  plot_annotation(tag_levels = 'A')

fig_div_full

# ggsave(fig_div_full,
#        filename = "figures/teton_34sites/divergences_paneled.jpg",
#        width = 12,
#        height = 5)



# End of script.
