## 3 rivers data output
## Created: October 13, 2021
## Heili Lowman

# The following code will do some examination of the output
# of the 3 site dataset run through the Ricker model to examine
# the effects of gappiness on time series.

# Load packages
lapply(c("calecopal", "cowplot",
         "lubridate","tidyverse", "reshape2",
         "PerformanceAnalytics","jpeg","grid",
         "rstan","bayesplot","shinystan", "here",
         "ggrepel", "patchwork"), require, character.only=T)

#### Data Import & Processing ####

# Load dataset loaded into STAN.
data_in <- readRDS("data_working/df_3sites.rds")

# Load datasets generated by STAN.
# output using full timeseries
data_out <- readRDS("data_working/stan_3rivers_output_Ricker_2021_10_13.rds")
# output using timeseries with gaps
data_out_g <- readRDS("data_working/stan_3rivers_gaps_output_Ricker_2021_10_13.rds")
# output of grouped yearly data for one site
data_out_y <- readRDS("data_working/stan_1river_years_output_Ricker_2021_10_13.rds")

# Load dataset with site information.
data_info <- readRDS("data_working/NWIS_3sitesinfo_subset.rds")

# Check out shinystan to see how things compare
# First, for the nwis_02266300 a.k.a. Reedy Creek, FL site
# Bad site
# where 3 years of data were removed
launch_shinystan(data_out$nwis_02266300)
launch_shinystan(data_out_g$nwis_02266300)
# things were a mess, and still look a mess after removing 3 yrs
# although divergences have decreased by 1000

# Next, for the nwis_14206950 a.k.a. Fanno Creek, OR site
# Medium site
# where 2 years of data were removed
launch_shinystan(data_out$nwis_14206950)
launch_shinystan(data_out_g$nwis_14206950)
# ~100 divergences before data removal, 
# none(!) after

# And finally for the nwis_01608500 a.k.a. South Branch Potomac
# River, WV site
# Good site
# where 1 year of data was removed
launch_shinystan(data_out$nwis_01608500)
launch_shinystan(data_out_g$nwis_01608500)
# none before, none after!!

# And we can compare these to the outcomes for each site-year
# divergences following each site-year
launch_shinystan(data_out_y$nwis_01608500_2008) # 13
launch_shinystan(data_out_y$nwis_01608500_2010) # 258
launch_shinystan(data_out_y$nwis_01608500_2012) # 24
launch_shinystan(data_out_y$nwis_01608500_2013) # 41
launch_shinystan(data_out_y$nwis_01608500_2014) # 32
launch_shinystan(data_out_y$nwis_01608500_2015) # 8
launch_shinystan(data_out_y$nwis_01608500_2016) # 676

# Function of the above to pull out data of interest from
# all sites.
extract_params <- function(df){
  extract(df, c("r","lambda","s","c","sig_p","sig_o"))
}

# And now map this to the output lists.
data_out_params <- map(data_out, extract_params)
data_out_params_g <- map(data_out_g, extract_params)
data_out_params_y <- map(data_out_y, extract_params)

# And create these lists into dataframes
data_out_params_df <- map_df(data_out_params, ~as.data.frame(.x), .id="site_name") %>%
  # and add "K" to it, calculating for each individual iteration
  mutate(k = (-1*r)/lambda) %>%
  mutate(Run = "Full Timeseries")

data_out_params_g_df <- map_df(data_out_params_g, ~as.data.frame(.x), .id="site_name") %>%
  mutate(k = (-1*r)/lambda) %>%
  mutate(Run = "Gappy Timeseries")

data_out_params_y_df <- map_df(data_out_params_y, ~as.data.frame(.x), .id="site_name") %>%
  mutate(k = (-1*r)/lambda) %>%
  mutate(Run = "Individual Site-Years")

df1 <- rbind(data_out_params_df, data_out_params_g_df)
df2 <- rbind(df1, data_out_params_y_df)

# And now to calculate means by site.
data_means <- df2 %>%
  group_by(Run, site_name) %>%
  summarize(r_mean = mean(r),
            k_mean = mean(k),
            s_mean = mean(s),
            c_mean = mean(c),
            sigp_mean = mean(sig_p),
            sigo_mean = mean(sig_o))

# Export dataset
saveRDS(data_means, file = "data_working/stan_3rivers_model_parameters_101421.rds")

# And create a figure to display differences by site-year

fig_sy <- data_means %>%
  filter(Run == "Individual Site-Years") %>%
  pivot_longer(cols = r_mean:sigo_mean,
               names_to = "parameter",
               values_to = "value") %>%
  mutate(year = case_when(site_name == "nwis_01608500_2008" ~ 2008,
                          site_name == "nwis_01608500_2010" ~ 2010,
                          site_name == "nwis_01608500_2012" ~ 2012,
                          site_name == "nwis_01608500_2013" ~ 2013,
                          site_name == "nwis_01608500_2014" ~ 2014,
                          site_name == "nwis_01608500_2015" ~ 2015,
                          site_name == "nwis_01608500_2016" ~ 2016)) %>%
  ggplot(aes(x = year, y = value, 
             fill = site_name)) +
  geom_point(shape = 21, size = 5) +
  scale_fill_manual(values = cal_palette("lake", n = 7, 
                                         type = "continuous")) +
  labs(x = "Site-Years",
       y = "Mean value of parameter") +
  facet_wrap(.~parameter, scales = "free") +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig_sy

# ggsave(plot = fig_sy,
#        filename = "figures/gap_experimenting/fig_sy_nwis_01608500_2.jpg",
#        width = 15,
#        height = 10)

# ...

# This time trying code suggested by Dan Ovando to extract divergences.

showClass("stanfit")
ecode <- '
  parameters {
    real<lower=0> y[2];
  } 
  model {
    y ~ exponential(1);
  }
'
fit <- stan(model_code = ecode, iter = 1000, chains = 2, warmup = 1)

rstan::check_hmc_diagnostics(fit)

list_way = get_sampler_params(fit, inc_warmup = FALSE)

n_divergent <- sum(sapply(list_way, function(x) sum(x[,"divergent__"])))

n_divergent

other_way_to_get_n_divergent <- rstan::get_num_divergent(fit)

other_way_to_get_n_divergent
# ...
# And now map this to the entire output list.
# this function can also be finicky, and require you to quit R and re-load everything back in.
data_out_divs <- map(data_out, extract_divergences)

# And create a dataframe
data_out_divs_df <- map_df(data_out_divs, ~as.data.frame(.x), .id="site_name") %>%
  rename(divergences = `.x`)

# Export dataset
saveRDS(data_out_divs_df, file = "data_working/teton_34rivers_model_divergences_091621.rds")

# End of script.
