## 3 rivers data output
## Created: October 13, 2021
## Heili Lowman

# The following code will do some examination of the output
# of the 3 site dataset run through the Ricker model to examine
# the effects of gappiness on time series.

# Load packages
lapply(c("calecopal", "cowplot",
         "lubridate","tidyverse", "reshape2",
         "PerformanceAnalytics","jpeg","grid",
         "rstan","bayesplot","shinystan", "here",
         "ggrepel", "patchwork"), require, character.only=T)

#### Data Import & Processing ####

# Load dataset loaded into STAN.
data_in <- readRDS("data_working/df_3sites.rds")

# Load datasets generated by STAN.
# output using full timeseries
data_out <- readRDS("data_working/stan_3rivers_output_Ricker_2021_10_13.rds")
# output using timeseries with gaps
data_out_g <- readRDS("data_teton/stan_3rivers_gaps_output_Ricker_2021_10_13.rds")
# output of grouped yearly data for one site
data_out_y <- readRDS("data_teton/stan_1river_years_output_Ricker_2021_10_13.rds")

# Load dataset with site information.
data_info <- readRDS("data_working/NWIS_3sitesinfo_subset.rds")

# Check out shinystan to see how things compare
# First, for the nwis_02266300 a.k.a. NAME HERE site
# where 3 years of data were removed
launch_shinystan(data_out$nwis_02266300)
launch_shinystan(data_out_g$nwis_02266300)
# And we can compare these to the outcomes for each site-year
launch_shinystan(data_out_y$nwis_02266300-2008)
launch_shinystan(data_out_y$nwis_02266300-2009)
launch_shinystan(data_out_y$nwis_02266300-2010)
launch_shinystan(data_out_y$nwis_02266300-2011)
launch_shinystan(data_out_y$nwis_02266300-2012)
launch_shinystan(data_out_y$nwis_02266300-2013)
launch_shinystan(data_out_y$nwis_02266300-2014)
launch_shinystan(data_out_y$nwis_02266300-2015)
launch_shinystan(data_out_y$nwis_02266300-2016)

# Next, for the nwis_14206950 a.k.a. NAME HERE site
# where 2 years of data were removed
launch_shinystan(data_out$nwis_14206950)
launch_shinystan(data_out_g$nwis_14206950)

# And finally for the nwis_01608500 a.k.a. NAME HERE site
# where 1 year of data was removed
launch_shinystan(data_out$nwis_01608500)
launch_shinystan(data_out_g$nwis_01608500)

# Function of the above to pull out data of interest from
# all sites.
extract_params <- function(df){
  extract(df, c("r","lambda","s","c","sig_p","sig_o"))
}

# And now map this to the output lists.
data_out_params <- map(data_out, extract_params)
data_out_params_g <- map(data_out_g, extract_params)
data_out_params_y <- map(data_out_y, extract_params)

# And create these lists into dataframes
data_out_params_df <- map_df(data_out_params, ~as.data.frame(.x), .id="site_name") %>%
  # and add "K" to it, calculating for each individual iteration
  mutate(k = (-1*r)/lambda) %>%
  mutate(Run = "Full Timeseries")

data_out_params_g_df <- map_df(data_out_params_g, ~as.data.frame(.x), .id="site_name") %>%
  mutate(k = (-1*r)/lambda) %>%
  mutate(Run = "Gappy Timeseries")

data_out_params_y_df <- map_df(data_out_params_y, ~as.data.frame(.x), .id="site_name") %>%
  mutate(k = (-1*r)/lambda) %>%
  mutate(Run = "Individual Site-Years")

df1 <- cbind(data_out_params_df, data_out_params_g_df)
df2 <- cbind(df1, data_out_params_y_df)

# And now to calculate means by site.
data_means <- df2 %>%
  group_by(Run, site_name) %>%
  summarize(r_mean = mean(r),
            k_mean = mean(k),
            s_mean = mean(s),
            c_mean = mean(c),
            sigp_mean = mean(sig_p),
            sigo_mean = mean(sig_o))

# And now to bind the values with site attributes.
# data_together <- left_join(data_means, data_info, by = "site_name")

# Export dataset
saveRDS(data_together, file = "data_working/teton_3rivers_model_parameters_101321.rds")

# This time trying code suggested by Dan Ovando to extract divergences.

showClass("stanfit")
ecode <- '
  parameters {
    real<lower=0> y[2];
  } 
  model {
    y ~ exponential(1);
  }
'
fit <- stan(model_code = ecode, iter = 1000, chains = 2, warmup = 1)

rstan::check_hmc_diagnostics(fit)

list_way = get_sampler_params(fit, inc_warmup = FALSE)

n_divergent <- sum(sapply(list_way, function(x) sum(x[,"divergent__"])))

n_divergent

other_way_to_get_n_divergent <- rstan::get_num_divergent(fit)

other_way_to_get_n_divergent
# ...
# And now map this to the entire output list.
# this function can also be finicky, and require you to quit R and re-load everything back in.
data_out_divs <- map(data_out, extract_divergences)

# And create a dataframe
data_out_divs_df <- map_df(data_out_divs, ~as.data.frame(.x), .id="site_name") %>%
  rename(divergences = `.x`)

# Export dataset
saveRDS(data_out_divs_df, file = "data_working/teton_34rivers_model_divergences_091621.rds")

#### All Parameter Comparisons ####

# Now, to compare growth and disturbance parameters
# r vs. c
fig5a <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = c_mean, y = r_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) + # custom colors
  labs(x = "Critical Discharge (c)",
       y = "Maximum Growth Rate (r)") +
  geom_text_repel(data = subset(data_together, r_mean > 0.3), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5a

# r vs. s
fig5b <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = s_mean, y = r_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Sensitivity of Persistence Curve (s)",
       y = "Maximum Growth Rate (r)") +
  geom_text_repel(data = subset(data_together, r_mean > 0.3 | s_mean > 300), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5b

# k vs. c
fig5c <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = c_mean, y = k_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Critical Discharge (c)",
       y = "Carrying Capacity (K)") +
  geom_text_repel(data = subset(data_together, k_mean > 30), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5c

# k vs. s
fig5d <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = s_mean, y = k_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Sensitivity of Persistence Curve (s)",
       y = "Carrying Capacity (K)") +
  geom_text_repel(data = subset(data_together, k_mean > 30 | s_mean > 300), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5d

full_fig5 <- (fig5a + fig5b) / (fig5c + fig5d) +
  plot_annotation(tag_levels = 'A')

full_fig5

# ggsave(full_fig5,
#        filename = "figures/teton_34sites/rk_vs_cs.jpg",
#        width = 11,
#        height = 11)

#### Covariate data quality ####

plotting_covar <- function(x) {
  
  # create a dataframe at each site
  df.1 <- x
  
  # join with site information
  df <- left_join(df.1, data_info, by = "site_name")
  
  # create a vector of the available years of data
  years <- unique(df$year)
  
  # loop over each year of data
  for(z in years){
    
    # subset the data by year
    subset <- subset(df, year == z) # subset the larger dataset by each year
    
    # create a 4-paneled plot with gross primary production, discharge, temperature, and light
    # a.k.a. data inputs (prior to fitting the model)
    p <- plot_grid(
    
    ggplot(subset, aes(date, GPP))+
      geom_point(color="chartreuse4", size=2)+
      geom_errorbar(aes(ymin = GPP.lower, ymax = GPP.upper), width=0.2,color="darkolivegreen4")+
      labs(y=expression('GPP (g '*~O[2]~ m^-2~d^-1*')'), 
           title = df$long_name.y[1],
           subtitle = df$site_name[1])+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, Q))+
      geom_line(size=1.5, color="deepskyblue4")+
      labs(y="Q (cms)")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, temp))+
      geom_line(size=1.5, color="#A11F22")+
      labs(y="Water Temp (C)")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, light))+
      geom_point(size=2, color="darkgoldenrod3")+
      labs(y="Incoming Light", x="Date")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.text = element_text(size=12),
            axis.title = element_text(size=12)),
    ncol=1, align="hv")
  
  # display plots
  print(p) 
  
  # save and export plots
  file.name <- paste0("figures/teton_34sites/site_covariate_plots/",df$site_name[1],"_",z,"_covar.jpg",sep = "") # create file name
  
  # set specifications for size and resolution of your figure
  ggsave(p,
         filename = file.name,
         width = 8,
         height = 8)
  
  } # close out for-loop
  
} # close out function

# test to be sure the function works at a single site
plotting_covar(data_in$nwis_02266200)

# And now map this to the entire data_in list.
map(data_in, plotting_covar)

# End of script.
