## 34 rivers data output from Teton
## Created: August 5, 2021
## Heili Lowman

# The following code will do some preliminary examination of the output
# of the 34 site dataset sent to Teton and run through the Ricker model
# earlier this week.

# Load packages
lapply(c("calecopal", "cowplot",
         "lubridate","tidyverse", "reshape2",
         "PerformanceAnalytics","jpeg","grid",
         "rstan","bayesplot","shinystan", "here",
         "ggrepel", "patchwork"), require, character.only=T)

#### Data Import & Processing ####

# Load dataset loaded into Teton.
data_in <- readRDS("data_working/df_34sites.rds")

# Load dataset generated by Teton (this is a biggie).
data_out <- readRDS("data_teton/stan_34rivers_output_Ricker_2021_08_03.rds")

# Load dataset with site information.
data_info <- readRDS("data_working/NWIS_34sitesinfo_subset.rds")

# Load dataset with years of data coverage at each site.
data_years <- readRDS("data_working/teton_34rivers_sitesyears.rds")

# Load dataset with all parameters included (code to generate this dataset is below).
data_together <- readRDS("data_working/teton_34rivers_model_parameters_090821.rds")

# Make sure shinystan is working properly by testing at one site.
launch_shinystan(data_out$nwis_01632900)
# It is working! Although I am getting an error message suggesting I trim
# the data down a bit before launching Shiny STAN.

# Make sure we can extract parameters by testing at one site.
test_params <- extract(data_out$nwis_01608500, c("r","lambda","s","c",
                                                 "B","P","pred_GPP","sig_p","sig_o"))
# Yay - this works too!

# Going to create a function of the above to pull out data of interest from
# all sites.
extract_params <- function(df){
  extract(df, c("r","lambda","s","c","sig_p","sig_o"))
}

# And now map this to the entire output list.
data_out_params <- map(data_out, extract_params)
# the above line of code sometimes doesn't play nicely if R has been up and running
# for awhile, so the fix is to exit RStudio and reopen the project/file

# And create a dataframe
data_out_params_df <- map_df(data_out_params, ~as.data.frame(.x), .id="site_name") %>%
  # and add "K" to it, calculating for each individual iteration
  mutate(k = (-1*r)/lambda)

# And now to calculate means by site.
data_means <- data_out_params_df %>%
  group_by(site_name) %>%
  summarize(r_mean = mean(r),
            k_mean = mean(k),
            s_mean = mean(s),
            c_mean = mean(c),
            sigp_mean = mean(sig_p),
            sigo_mean = mean(sig_o))

# And now to bind the values with site attributes.
data_together <- left_join(data_means, data_info, by = "site_name")

# Export dataset
saveRDS(data_together, file = "data_working/teton_34rivers_model_parameters_090821.rds")

# Also, need to extract divergence information from the sites.
# Code available at : mc-stan.org/users/documentation/case-studies/divergences_and_bias.html
# Doing this at one site first to make sure it works - note nwis_01632900 has 8 divergences.
# Note - you need TWO underscores after 'divergent'
divergent <- get_sampler_params(data_out$nwis_01632900, inc_warmup=FALSE)[[1]][,'divergent__']
sum(divergent)
# Yay, it works!!

# Now, to map this to the whole dataset
extract_divergences <- function(df){
  divergent <- get_sampler_params(df, inc_warmup=FALSE)[[1]][,'divergent__']
  sum(divergent)
}

# And now map this to the entire output list.
# this function can also be finicky, and require you to quit R and re-load everything back in.
data_out_divs <- map(data_out, extract_divergences)
# WOOHOO!!

# And create a dataframe
data_out_divs_df <- map_df(data_out_divs, ~as.data.frame(.x), .id="site_name") %>%
  rename(divergences = `.x`)

# Export dataset
saveRDS(data_out_divs_df, file = "data_working/teton_34rivers_model_divergences_091621.rds")

# Import dataset with divergences from two different methods
data_out_diff_divs <- read_csv("data_working/divergences_09_21_21.csv")

# Save out two additional datasets for use in the divergences reprex script.
# Commenting these out, because they ended up being too large to push to GitHub.
# site1 <- data_out$nwis_01632900
# saveRDS(site1, file = "code/teton_34sites/div_reprex/output_nwis_01632900.rds")
# 
# site2 <- data_out$nwis_01645704
# saveRDS(site2, file = "code/teton_34sites/div_reprex/output_nwis_01645704.rds")

####      Figures         ####

#### Max Growth Rate / Carrying Capacity ####

# Basic plot of r values vs. stream order.
fig1 <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  mutate(so = factor(NHD_STREAMORDE)) %>%
  ggplot(aes(x = so, y = r_mean, fill = so)) +
  scale_fill_manual(values = cal_palette("sbchannel", n = 7, type = "continuous")) + # custom colors
  geom_boxplot(alpha = 0.75) +
  geom_jitter(color = "black", alpha = 0.5, width = 0.1) +
  labs(x = "NHD Stream Order",
       y = "Maximum Growth Rate (r)") +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig1

# ggsave(plot = fig1,
#        filename = "figures/teton_34sites/r_strord.jpg",
#        width = 8,
#        height = 6)

fig2 <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  mutate(so = factor(NHD_STREAMORDE)) %>%
  ggplot(aes(x = so, y = k_mean, fill = so)) +
  scale_fill_manual(values = cal_palette("sbchannel", n = 7, type = "continuous")) + # custom colors
  geom_boxplot(alpha = 0.75) +
  geom_jitter(color = "black", alpha = 0.5, width = 0.1) +
  labs(x = "NHD Stream Order",
       y = "Carrying Capacity (K)") +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig2

# ggsave(plot = fig2,
#        filename = "figures/teton_34sites/k_strord.jpg",
#        width = 8,
#        height = 6)

# After updating the code on Aug 12, here are some additional figures.
# Made additional edits to the code below for rmarkdown figure creation, 9/9/21.
# First, a quick pairs plot.
fig_pairs <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  select(r_mean, k_mean, s_mean, c_mean, NHD_STREAMORDE) %>%
  pairs()

# Now, to plot the growth parameters.
fig3a <- ggplot(data_together, aes(x = r_mean, y = k_mean, 
                                  fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 4, alpha = 0.75) +
  labs(x = "Maximum Growth Rate (r)",
       y = "Carrying Capacity (K)",
       title = "Full Dataset") +
  geom_text_repel(size=3) +
  theme_bw() +
  theme(legend.position = "none")

fig3a

# Removing negative r and K values.
fig3b <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = r_mean, y = k_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) + # custom colors
  labs(x = "Maximum Growth Rate (r)",
       y = "Carrying Capacity (K)") +
  geom_text_repel(data = subset(data_together, r_mean > 0.4), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig3b

# Create single figure of r, k, and stream order figures:
fig1_full <- fig1 + fig2 + fig3b +
  plot_annotation(tag_levels = 'A')

fig1_full

# ggsave(plot = fig1_full,
#        filename = "figures/teton_34sites/r_k_paneled.jpg",
#        width = 15,
#        height = 5)

# Panel by stream order with negative growth parameters removed
fig3c <- data_together %>%
    filter(r_mean > 0) %>%
    filter(k_mean > 0) %>%
    ggplot(aes(x = r_mean, y = k_mean, fill = site_name)) +
    geom_point(shape = 21, size = 4, alpha = 0.75) +
    labs(x = "Maximum Growth Rate (r)",
         y = "Carrying Capacity (K)",
         title = "Paneled by Stream Order - Negative Values Removed") +
    facet_wrap(~NHD_STREAMORDE, scales = "free", ncol = 4)+
    #geom_text_repel(size=3) +
    theme_bw() +
    theme(legend.position = "none")

fig3c

# creating composite figure for export
full_fig3 <- (fig3a + fig3b) / fig3c 

full_fig3

# ggsave(full_fig3,
#        filename = "figures/teton_34sites/k_vs_r.jpg",
#        width = 8,
#        height = 8)

#### Critical Discharge / Sensitivity of Persistence Curve ####

# and exploring disturbance metrics
fig4a <- ggplot(data_together, aes(x = c_mean, y = s_mean, 
                                   fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 4, alpha = 0.75) +
  labs(x = "Critical Discharge (c)",
       y = "Sensitivity of Persistence Curve (s)",
       title = "Full Dataset") +
  geom_text_repel(size=3) +
  theme_bw() +
  theme(legend.position = "none")

fig4a

# Removing negative r and K values.
fig4b <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = c_mean, y = s_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  labs(x = "Critical Discharge (c)",
       y = "Sensitivity of Persistence Curve (s)") +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) + # custom colors
  geom_text_repel(data = subset(data_together, c_mean < 0.25 & s_mean > 250), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig4b

# Panel by stream order with negative growth parameters removed
fig4c <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = c_mean, y = s_mean, fill = site_name)) +
  geom_point(shape = 21, size = 4, alpha = 0.75) +
  labs(x = "Critical Discharge (c)",
       y = "Steepness of Persistence Curve (s)",
       title = "Paneled by Stream Order - Negative Values Removed") +
  facet_wrap(~NHD_STREAMORDE, scales = "free", ncol = 4)+
  theme_bw() +
  theme(legend.position = "none")

fig4c

# Creating some boxplots for s and c as well

# Basic plot of s values vs. stream order.
fig2.1 <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  mutate(so = factor(NHD_STREAMORDE)) %>%
  ggplot(aes(x = so, y = s_mean, fill = so)) +
  scale_fill_manual(values = cal_palette("sbchannel", n = 7, type = "continuous")) + # custom colors
  geom_boxplot(alpha = 0.75) +
  geom_jitter(color = "black", alpha = 0.5, width = 0.1) +
  labs(x = "NHD Stream Order",
       y = "Sensitivity of Persistence Curve (s)") +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig2.1

# Basic plot of c values vs. stream order.
fig2.2 <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  mutate(so = factor(NHD_STREAMORDE)) %>%
  ggplot(aes(x = so, y = c_mean, fill = so)) +
  scale_fill_manual(values = cal_palette("sbchannel", n = 7, type = "continuous")) + # custom colors
  geom_boxplot(alpha = 0.75) +
  geom_jitter(color = "black", alpha = 0.5, width = 0.1) +
  labs(x = "NHD Stream Order",
       y = "Critical Discharge (c)") +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig2.2

# creating composite figure for export
fig2_full <- fig2.1 + fig2.2 + fig4b +
  plot_annotation(tag_levels = 'A')

fig2_full

# ggsave(fig2_full,
#        filename = "figures/teton_34sites/s_c_paneled.jpg",
#        width = 15,
#        height = 5)

#### All Parameter Comparisons ####

# Now, to compare growth and disturbance parameters
# r vs. c
fig5a <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = c_mean, y = r_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) + # custom colors
  labs(x = "Critical Discharge (c)",
       y = "Maximum Growth Rate (r)") +
  geom_text_repel(data = subset(data_together, r_mean > 0.3), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5a

# r vs. s
fig5b <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = s_mean, y = r_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Sensitivity of Persistence Curve (s)",
       y = "Maximum Growth Rate (r)") +
  geom_text_repel(data = subset(data_together, r_mean > 0.3 | s_mean > 300), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5b

# k vs. c
fig5c <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = c_mean, y = k_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Critical Discharge (c)",
       y = "Carrying Capacity (K)") +
  geom_text_repel(data = subset(data_together, k_mean > 30), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5c

# k vs. s
fig5d <- data_together %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  ggplot(aes(x = s_mean, y = k_mean, 
             fill = site_name, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("creek", n = 28, type = "continuous")) +
  labs(x = "Sensitivity of Persistence Curve (s)",
       y = "Carrying Capacity (K)") +
  geom_text_repel(data = subset(data_together, k_mean > 30 | s_mean > 300), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig5d

full_fig5 <- (fig5a + fig5b) / (fig5c + fig5d) +
  plot_annotation(tag_levels = 'A')

full_fig5

# ggsave(full_fig5,
#        filename = "figures/teton_34sites/rk_vs_cs.jpg",
#        width = 11,
#        height = 11)

#### Covariate data quality ####

plotting_covar <- function(x) {
  
  # create a dataframe at each site
  df.1 <- x
  
  # join with site information
  df <- left_join(df.1, data_info, by = "site_name")
  
  # create a vector of the available years of data
  years <- unique(df$year)
  
  # loop over each year of data
  for(z in years){
    
    # subset the data by year
    subset <- subset(df, year == z) # subset the larger dataset by each year
    
    # create a 4-paneled plot with gross primary production, discharge, temperature, and light
    # a.k.a. data inputs (prior to fitting the model)
    p <- plot_grid(
    
    ggplot(subset, aes(date, GPP))+
      geom_point(color="chartreuse4", size=2)+
      geom_errorbar(aes(ymin = GPP.lower, ymax = GPP.upper), width=0.2,color="darkolivegreen4")+
      labs(y=expression('GPP (g '*~O[2]~ m^-2~d^-1*')'), 
           title = df$long_name.y[1],
           subtitle = df$site_name[1])+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, Q))+
      geom_line(size=1.5, color="deepskyblue4")+
      labs(y="Q (cms)")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, temp))+
      geom_line(size=1.5, color="#A11F22")+
      labs(y="Water Temp (C)")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.title.x = element_blank(), axis.text.x = element_blank(),
            axis.text.y = element_text(size=12),
            axis.title.y = element_text(size=12)),
    
    ggplot(subset, aes(date, light))+
      geom_point(size=2, color="darkgoldenrod3")+
      labs(y="Incoming Light", x="Date")+
      theme(legend.position = "none",
            panel.background = element_rect(color = "black", fill=NA, size=1),
            axis.text = element_text(size=12),
            axis.title = element_text(size=12)),
    ncol=1, align="hv")
  
  # display plots
  print(p) 
  
  # save and export plots
  file.name <- paste0("figures/teton_34sites/site_covariate_plots/",df$site_name[1],"_",z,"_covar.jpg",sep = "") # create file name
  
  # set specifications for size and resolution of your figure
  ggsave(p,
         filename = file.name,
         width = 8,
         height = 8)
  
  } # close out for-loop
  
} # close out function

# test to be sure the function works at a single site
plotting_covar(data_in$nwis_02266200)

# And now map this to the entire data_in list.
map(data_in, plotting_covar)

#### Light vs. Growth Parameters ####

# Create a function to calculate mean light availability
calc_mean_light <- function(df){
  mean(df$PAR_new) # this column either pulls light from Appling or PAR_surface from Savoy
}

# And now map this to the entire output list.
data_light <- map(data_in, calc_mean_light)

# And create a dataframe
data_light_params <- map_df(data_light, ~as.data.frame(.x), .id="site_name") %>%
  rename(light_mean = `.x`) %>%
  left_join(data_together, by = "site_name")

# Light vs.maximum growth rate
# light vs. r
fig_light1 <- data_light_params %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  mutate(light_cat = factor(light_mean)) %>% # adding column for coloration purposes
  ggplot(aes(x = light_mean, y = r_mean, fill = light_cat)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("canary", n = 28, type = "continuous")) + # custom colors
  labs(x = "Light Availability (ppfd?)",
       y = "Maximum Growth Rate (r)") +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig_light1

# Light vs.carrying capacity
# light vs. K
fig_light2 <- data_light_params %>%
  filter(r_mean > 0) %>%
  filter(k_mean > 0) %>%
  mutate(light_cat = factor(light_mean)) %>% # adding column for coloration purposes
  ggplot(aes(x = light_mean, y = k_mean, fill = light_cat)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("canary", n = 28, type = "continuous")) + # custom colors
  labs(x = "Light Availability (ppfd?)",
       y = "Carrying Capacity (K)") +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig_light2

#### Divergences ####

# fig_div <- ggplot(data_out_divs_df, aes(x = bin_cat, fill = bin_cat)) + # base plot
#   geom_histogram(stat = "count") + # divergences histogram
#   scale_fill_manual(values = cal_palette("fire", n = 7, type = "continuous")) + # custom colors
#   labs(x = "Number of Divergences",
#        y = "Site Count") +
#   scale_y_continuous(breaks=seq(0, 10, 1)) + # fix y axis labels
#   theme_classic() + # remove grid
#   theme(legend.position = "none")
# 
# fig_div
# DONT USE THIS FIGURE YET - for whatever reason, the 
# number of divergences on the shinystan app does not
# match the output of the above function from the mc-stan
# help document....

# For the meeting on 9/27/2021, I will be using the output of shinystan since,
# it's the larger/more conservative

data_divs_join <- left_join(data_years, data_out_diff_divs, by = "site_name")

# Adding category to make a nicer looking plots
data_divs_join <- data_divs_join %>%
  mutate(bin_cat = factor(case_when(div_shinyStan == 0 ~ "0",
                                    div_shinyStan > 0 & div_shinyStan <= 50 ~ "0-50",
                                    div_shinyStan > 50 & div_shinyStan <= 100 ~ "50-100",
                                    div_shinyStan > 100 & div_shinyStan <= 1000 ~ "100-1000",
                                    div_shinyStan > 1000 & div_shinyStan <= 2500 ~ "1000-2500",
                                    div_shinyStan > 2500 ~ "2500+",
                                    TRUE ~ "NA"),
                          levels = c("0", "0-50", "50-100", "100-1000", "1000-2500", "2500+")))

fig_yrs_divs <- ggplot(data_divs_join,
                       aes(x = n, y = div_shinyStan, fill = bin_cat, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("fire", n = 6, type = "continuous")) + # custom colors
  labs(x = "Years of Available Data",
       y = "Divergent Transitions") +
  geom_text_repel(data = subset(data_divs_join, n > 5 & div_shinyStan > 2000), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig_yrs_divs

# Also creating figure of hydrology vs. divergences

# Calculate coefficient of variation (sd/mean) for each site
test_site <- data_in$nwis_01608500
test_sd <- sd(test_site$Q)
test_mean <- mean(test_site$Q)
test_cv <- test_sd/test_mean

# Now, to create a function...
calc_coeff_var <- function(df){
  sd <- sd(df$Q)
  mean <- mean(df$Q)
  sd/mean
}

# And now map this to the entire output list.
data_cvs <- map(data_in, calc_coeff_var)
# yipee

# And create a dataframe
data_cvs_divs <- map_df(data_cvs, ~as.data.frame(.x), .id="site_name") %>%
  rename(coeff_var = `.x`) %>%
  left_join(data_out_diff_divs, by = "site_name")

# Adding same categories as above to make a nicer looking plots
data_cvs_divs <- data_cvs_divs %>%
  mutate(bin_cat = factor(case_when(div_shinyStan == 0 ~ "0",
                                    div_shinyStan > 0 & div_shinyStan <= 50 ~ "0-50",
                                    div_shinyStan > 50 & div_shinyStan <= 100 ~ "50-100",
                                    div_shinyStan > 100 & div_shinyStan <= 1000 ~ "100-1000",
                                    div_shinyStan > 1000 & div_shinyStan <= 2500 ~ "1000-2500",
                                    div_shinyStan > 2500 ~ "2500+",
                                    TRUE ~ "NA"),
                          levels = c("0", "0-50", "50-100", "100-1000", "1000-2500", "2500+")))

fig_cv_divs <- ggplot(data_cvs_divs,
                       aes(x = coeff_var, y = div_shinyStan, fill = bin_cat, label = site_name)) +
  geom_point(shape = 21, size = 5, alpha = 0.75) +
  scale_fill_manual(values = cal_palette("fire", n = 6, type = "continuous")) + # custom colors
  labs(x = "Coefficient of Variation in Discharge",
       y = "Divergent Transitions") +
  geom_text_repel(data = subset(data_cvs_divs, coeff_var > 3 | div_shinyStan > 3000), size = 4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none")

fig_cv_divs

# creating composite figure for export
fig_div_full <- fig_yrs_divs + fig_cv_divs +
  plot_annotation(tag_levels = 'A')

fig_div_full

# ggsave(fig_div_full,
#        filename = "figures/teton_34sites/divergences_paneled.jpg",
#        width = 12,
#        height = 5)

#### Check model diagnostics ####

# Using rstan documentation found at:
# https://mc-stan.org/rstan/articles/stanfit_objects.html

# Obtain summary statistics for a single site
test_summary <- summary(data_out$nwis_01608500)

# In $summary, results for all chains are merged
print(test_summary$summary)
# se_mean = Monte Carlo standard error
# n_eff = effective sample size
# Rhat = R-hat statistic

# Obtain summary statistics for a single site for particular parameters
# Essentially combining top two steps into a single one
test_summary2 <- summary(data_out$nwis_01608500, 
                         pars = c("r","lambda","s","c"))$summary

# Need to move rownames to their own column
test_summary3 <- as.data.frame(test_summary2) %>%
  rownames_to_column("parameter")

# Ok, so this is working, now I need to iterate over all sites
# and combine model diagnostics for r, lambda, s, and c

# Using a similar workflow as above:
# Going to create a function of the above to pull out summaries from all sites
extract_summary <- function(x){
  df <- x
  df1 <- summary(df,
          pars = c("r", "lambda", "s", "c"))$summary
  as.data.frame(df1) %>% rownames_to_column("parameter")
}

# And now map this to the entire output list.
data_out_summary <- map(data_out, extract_summary)

# And create a dataframe
data_out_summary_df <- map_df(data_out_summary, ~as.data.frame(.x), .id="site_name")

# And now to bind the values with site attributes.
data_summary_siteinfo <- left_join(data_out_summary_df, data_info, by = "site_name")

# Export dataset
#saveRDS(data_summary_siteinfo, file = "data_working/teton_34rivers_model_diagnostics_090821.rds")

# Load in this dataset
data_summary_siteinfo <- readRDS("data_working/teton_34rivers_model_diagnostics_090821.rds")

# Mimic the s vs. c plot created above, but this time with confidence intervals added.
# Careful, I am not filtering out negative r and k values here for now (just for a rough
# estimate of intervals about the mean).
data_summary_wide <- data_summary_siteinfo %>%
  filter(parameter == "s" | parameter == "c") %>%
  select(site_name, parameter, mean, `2.5%`, `97.5%`) %>%
  pivot_wider(names_from = parameter, values_from = c(mean, `2.5%`, `97.5%`))

fig_sc_ci.1 <- ggplot(data_summary_wide, aes(x = mean_c, y = mean_s, 
                                   fill = site_name)) + # , label = site_name
  geom_point(shape = 21, size = 4, alpha = 0.75) +
  labs(x = "Critical Discharge (c)",
       y = "Sensitivity of Persistence Curve (s)") +
  xlim(0, 3) +
  ylim(0, 600) +
  geom_errorbar(aes(ymin = `2.5%_s`,ymax = `97.5%_s`)) + 
  #geom_errorbarh(aes(xmin = `2.5%_c`,xmax = `97.5%_c`)) +
  #geom_text_repel(size=3) +
  scale_fill_manual(values = cal_palette("creek", n = 34, type = "continuous")) + # custom colors
  theme_bw() +
  theme(legend.position = "none")

fig_sc_ci.1

fig_sc_ci.2 <- ggplot(data_summary_wide, aes(x = mean_c, y = mean_s, 
                                             fill = site_name)) + # , label = site_name
  geom_point(shape = 21, size = 4, alpha = 0.75) +
  labs(x = "Critical Discharge (c)",
       y = "Sensitivity of Persistence Curve (s)") +
  xlim(0, 3) +
  ylim(0, 600) +
  #geom_errorbar(aes(ymin = `2.5%_s`,ymax = `97.5%_s`)) + 
  geom_errorbarh(aes(xmin = `2.5%_c`,xmax = `97.5%_c`)) +
  #geom_text_repel(size=3) +
  scale_fill_manual(values = cal_palette("creek", n = 34, type = "continuous")) + # custom colors
  theme_bw() +
  theme(legend.position = "none")

fig_sc_ci.2

fig_sc_ci_full <- fig_sc_ci.1 + fig_sc_ci.2

fig_sc_ci_full

# Export figure, but don't include in RMarkdown for clarity's sake.
# ggsave(fig_sc_ci_full,
#        filename = "figures/teton_34sites/s_vs_c_withcis.jpg",
#        width = 12,
#        height = 5)

# End of script.
