## 34 rivers data output from Teton
## Created: August 5, 2021
## Heili Lowman

# The following code will do some preliminary examination of the output
# of the 34 site dataset sent to Teton and run through the Ricker model
# earlier this week.

# Load packages
lapply(c("plyr","dplyr","ggplot2","cowplot",
         "lubridate","tidyverse", "reshape2",
         "PerformanceAnalytics","jpeg","grid",
         "rstan","bayesplot","shinystan", "here"), require, character.only=T)

##############################
## Data Import & Processing ##
##############################

# Load dataset loaded into Teton.
data_in <- readRDS("data_working/df_34sites.rds")

# Load dataset generated by Teton (this is a biggie).
data_out <- readRDS("data_teton/stan_34rivers_output_Ricker_2021_08_03.rds")

# Load dataset with site information.
data_info <- readRDS("data_working/NWIS_34sitesinfo_subset.rds")

# Make sure shinystan is working properly by testing at one site.
launch_shinystan(data_out$nwis_01608500)
# It is working! Although I am getting an error message suggesting I trim
# the data down a bit before launching Shiny STAN.

# Make sure we can extract parameters by testing at one site.
test_params <- extract(data_out$nwis_01608500, c("r","lambda","s","c",
                                                 "B","P","pred_GPP","sig_p","sig_o"))
# Yay - this works too!

# Going to create a function of the above to pull out data of interest from
# all sites.
extract_params <- function(df){
  extract(df, c("r","lambda","s","c","B","P","pred_GPP","sig_p","sig_o"))
}

# And now map this to the entire output list.
data_out_params <- map(data_out, extract_params)

# And transform into a dataframe for easier plotting/manipulation.
# data_out_tibble <- data_out_params %>%
#   unlist(recursive = FALSE) %>% 
#   enframe() %>% 
#   unnest() # this proved too large/had uncompatible list lengths.

# So, breaking it down even further just to examine "r" values first.
# Create function to pull out "r" values and calculate means across sites.
extract_means <- function(df){
  new_df <- as.data.frame(df)
  
  new_df %>%
    summarize(mean_r = mean(r), mean_l = mean(lambda))
}

# And now map this to the entire output list.
data_out_means <- map(data_out_params, extract_means)

# And now turn it into a dataframe.
# First, turn all the nested lists into dataframes within a single list.
# dfs <- lapply(data_out_meanr, data.frame, stringsAsFactors = FALSE)
# Then, bind them all together.
# data_out_r_df <- dfs %>%
#   bind_rows()

# Another way of doing things to include list name (for site numbers).
data_out_r_df2 <- map_df(data_out_means, ~as.data.frame(.x), .id="id")

# And now to bind the values with site attributes.
data_together <- left_join(data_out_r_df2, data_info, by = c("id" = "site_name"))

# Calculate  k.
data_together <- data_together %>%
  mutate(mean_k = mean_r/mean_l)

# Basic plot of r values vs. stream order.
fig1 <- ggplot(data_together, aes(x = NHD_STREAMORDE, y = mean_r, fill = NHD_STREAMORDE)) +
  geom_point(shape = 21, size = 4, alpha = 0.75) +
  labs(x = "NHD Stream Order",
       y = "Maximum Growth Rate (r)") +
  theme_bw() +
  theme(legend.position = "none")

fig1

# three outliers - right to left - are Black Earth Creek WI, Reedy Creek FL, and Au Sable River FL

# ggsave(plot = fig1,
#        filename = "figures/teton_34sites/fig1_r_strord.jpg",
#        width = 8,
#        height = 6)

fig2 <- ggplot(data_together, aes(x = NHD_STREAMORDE, y = mean_k, fill = NHD_STREAMORDE)) +
  geom_point(shape = 21, size = 4, alpha = 0.75) +
  labs(x = "NHD Stream Order",
       y = "Carrying Capacity (k)") +
  theme_bw() +
  theme(legend.position = "none")

fig2

# outlier is again Reedy Creek FL

# ggsave(plot = fig2,
#        filename = "figures/teton_34sites/fig2_k_strord.jpg",
#        width = 8,
#        height = 6)

# End of script.
