## 207 rivers data output from Teton
## Created: February 6, 2022
## Heili Lowman

# The following code will do some preliminary processing of the output
# of the 207 site dataset sent to Teton and run through the Ricker model
# earlier this week.

# Due to the sheer size of the output of the dataset, the majority of
# the visualization code has been moved to TetonOutput_exploration.R.

# The first part of the code will include only the output of the version
# with the P term included.

# This will also include a second section in which the output from the
# run with the P term removed will also be processed and prepared for
# analysis/inclusion in the Rmarkdown document.

# Load packages
lapply(c("calecopal", "cowplot",
         "lubridate","tidyverse", "reshape2",
         "PerformanceAnalytics","jpeg","grid",
         "rstan","bayesplot","shinystan", "here",
         "ggrepel", "patchwork", "grid","gridExtra"), require, character.only=T)

#### Data Import & Processing ####

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DOES NOT WORK ON OFFICE DESKTOP ALONE.
# MUST LOAD THIS DATASET USING RSTUDIO ON PINYON SERVER.
# Load dataset generated by Teton (this is a biggie = 80GB).
# Be patient - this takes ~ 1.5 hours or so.
data_out <- readRDS("data_teton/teton_207rivers_output_Ricker_2022_01_27.rds")
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# Make sure we can extract parameters by testing at one site.
test_params <- extract(data_out$nwis_01608500, c("r","lambda","s","c"))
# Yay - this works!

# Going to create a function of the above to pull out data of interest from
# all sites. Sticking to just the four parameters of interest for initial data viz.
extract_params <- function(df){
  extract(df, c("r","lambda","s","c"))
}

# And now map this to the entire output list.
data_out_params <- map(data_out, extract_params)
# the above line of code sometimes doesn't play nicely if R has been up and running
# for awhile, so the fix is to exit RStudio and reopen the project/file
# OR, as is the case with this code, where data_out has just taken an hour to load,
# you should instead uncheck and re-check 'rstan' so that it's extract function
# takes precedence over the same function in the 'tidyr' package.

# And create a dataframe
data_out_params_df <- map_df(data_out_params, ~as.data.frame(.x), .id="site_name") %>%
  # and add "K" to it, calculating for each individual iteration
  mutate(k = (-1*r)/lambda)

# Export dataset
# saveRDS(data_out_params_df, 
#        file = "data_working/teton_207rivers_model_parameters_all_iterations_020622.rds")

#### EXTRACTED GPP APRIL 30, 2022####

# Make sure we can extract gpp by testing at one site.
test_gpp <- extract(data_out$nwis_01608500, c("pred_GPP"))
# Yay - this works!

# Going to create a function of the above to pull out data of interest from
# all sites.
extract_gpp <- function(df){
  extract(df, c("pred_GPP"))
}

# And now map this to the entire output list.
data_out_gpp <- map(data_out, extract_gpp)
# the above line of code sometimes doesn't play nicely if R has been up and running
# for awhile, so the fix is to exit RStudio and reopen the project/file
# OR, as is the case with this code, where data_out has just taken an hour to load,
# you should instead uncheck and re-check 'rstan' so that it's extract function
# takes precedence over the same function in the 'tidyr' package.

# And create a dataframe - patience, this also takes a minute
data_out_gpp_df <- map_df(data_out_gpp, ~as.data.frame(.x), .id="site_name")

# Export dataset
# saveRDS(data_out_gpp_df,
#        file = "data_working/teton_207rivers_model_predgpp_all_iterations_020622.rds")

#### Divergences ####

# Also, need to extract divergence information from the sites.
# Code available at : mc-stan.org/users/documentation/case-studies/divergences_and_bias.html
# Doing this at one site first to make sure it works - note nwis_01632900 has 8 divergences.
# Note - you need TWO underscores after 'divergent'
# divergent <- get_sampler_params(data_out$nwis_01632900, inc_warmup=FALSE)[[1]][,'divergent__']
# sum(divergent)
# Yay, it works!!

# Another method for extrating divergences per the stan handbook:
# mc-stan.org/rstan/reference/check_hmc_diagnostics.html
test_div <- as.numeric(get_num_divergent(data_out$nwis_01632900)) # 19

# Checking to see if the shinystan output is the same
launch_shinystan(data_out$nwis_01632900) # also 19, YAY!!!

# Now, to map this to the whole dataset
# extract_divergences <- function(df){
#   divergent <- get_sampler_params(df, inc_warmup=FALSE)[[1]][,'divergent__']
#   sum(divergent)
# }

extract_divergences <- function(df){
  divergences <- as.numeric(get_num_divergent(df))
}

# And now map this to the entire output list.
# this function can also be finicky, and require you to quit R and re-load everything back in.
data_out_divergences <- map(data_out, extract_divergences)
# WOOHOO!!

# And create a dataframe
data_out_divergences_df <- map_df(data_out_divergences, ~as.data.frame(.x), .id="site_name") %>%
  rename(divergences = `.x`)

# Export dataset
# saveRDS(data_out_divergences_df, file = "data_working/teton_207rivers_model_divergences_020622.rds")

#### Check model diagnostics ####

# Using rstan documentation found at:
# https://mc-stan.org/rstan/articles/stanfit_objects.html

# Obtain summary statistics for a single site
test_summary <- summary(data_out$nwis_01608500)

# In $summary, results for all chains are merged
print(test_summary$summary)
# se_mean = Monte Carlo standard error
# n_eff = effective sample size
# Rhat = R-hat statistic

# Obtain summary statistics for a single site for particular parameters
# Essentially combining top two steps into a single one
test_summary2 <- summary(data_out$nwis_01608500, 
                         pars = c("r","lambda","s","c"))$summary

# Need to move rownames to their own column
test_summary3 <- as.data.frame(test_summary2) %>%
  rownames_to_column("parameter")

# Ok, so this is working, now I need to iterate over all sites
# and combine model diagnostics for r, lambda, s, and c

# Using a similar workflow as above:
# Going to create a function of the above to pull out summaries from all sites
extract_summary <- function(x){
  df <- x
  df1 <- summary(df,
          pars = c("r", "lambda", "s", "c"))$summary
  as.data.frame(df1) %>% rownames_to_column("parameter")
}

# And now map this to the entire output list. (Be patient - this step takes a while.)
data_out_summary <- map(data_out, extract_summary)

# And create a dataframe
data_out_summary_df <- map_df(data_out_summary, ~as.data.frame(.x), .id="site_name")

# Export dataset
# saveRDS(data_out_summary_df, file = "data_working/teton_207rivers_model_diagnostics_020622.rds")

#### RUN WITH P TERM REMOVED ####

#### Data Import & Processing ####

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DOES NOT WORK ON OFFICE DESKTOP ALONE.
# MUST LOAD THIS DATASET USING RSTUDIO ON PINYON SERVER.
# Load dataset generated by Teton (this is a biggie = 30GB).
# Be patient - this takes ~ 45 minutes or so.
# data_out2 <- readRDS("data_teton/teton_131rivers_output_Ricker_2022_02_07.rds")
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# Create new "extract_params2" function created above to map to entire output list.
extract_params2 <- function(df){
  extract(df, c("r","lambda"))
}

data_out_params2 <- map(data_out2, extract_params2)

# And create a dataframe
data_out_params_df2 <- map_df(data_out_params2, ~as.data.frame(.x), .id="site_name") %>%
  # and add "K" to it, calculating for each individual iteration
  mutate(k = (-1*r)/lambda)

# Export dataset
# saveRDS(data_out_params_df2, 
#         file = "data_working/teton_131rivers_model_parameters_all_iterations_021322.rds")

#### Divergences ####

# Method for extracting divergences per the stan handbook:
# mc-stan.org/rstan/reference/check_hmc_diagnostics.html
# Use the "extract_divergences" functions created above.
data_out_divergences2 <- map(data_out2, extract_divergences)
# WOOHOO!!

# And create a dataframe
data_out_divergences_df2 <- map_df(data_out_divergences2, ~as.data.frame(.x), .id="site_name") %>%
  rename(divergences = `.x`)

# Export dataset
# saveRDS(data_out_divergences_df2, file = "data_working/teton_131rivers_model_divergences_021322.rds")

#### Check model diagnostics ####

# Using rstan documentation found at:
# https://mc-stan.org/rstan/articles/stanfit_objects.html

# Obtain summary statistics using new "extract_summary2" function.
extract_summary2 <- function(x){
  df <- x
  df1 <- summary(df,
                 pars = c("r", "lambda"))$summary
  as.data.frame(df1) %>% rownames_to_column("parameter")
}

# And now map this to the entire output list. (Be patient - this step takes a while.)
data_out_summary2 <- map(data_out2, extract_summary2)

# And create a dataframe
data_out_summary_df2 <- map_df(data_out_summary2, ~as.data.frame(.x), .id="site_name")

# Export dataset
#saveRDS(data_out_summary_df2, file = "data_working/teton_131rivers_model_diagnostics_021322.rds")

# End of script.
